version: '3'
services:
  # app:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - db
  #   environment:
  #     - DATABASE_URL=postgres://postgres:password@db:5432/bookworm

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: bookworm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'pgadmin4@pgadmin.org'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
    ports:
      - '5050:80'
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
